import argparse
import json

from .core import check, coverage, generate, validate
from .cubemx import ingest, packet, reconcile
from .compatibility import write_reports
from pathlib import Path


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("command", choices=["validate", "generate", "check", "coverage", "cubemx-ingest", "cubemx-reconcile", "cubemx-packet", "compatibility"])
    parser.add_argument("--cubemx-root")
    parser.add_argument("--cubemx-identity", default="STM32G0B1CBTx")
    parser.add_argument("--output")
    parser.add_argument("--pin", action="append", default=[])
    args = parser.parse_args()
    if args.command == "validate":
        validate(args.cubemx_root, args.cubemx_identity)
        print("upstream bundle valid")
    elif args.command == "generate":
        generate(args.cubemx_root, args.cubemx_identity)
        print("generated by upstream pcbir.devicegen")
    elif args.command == "check":
        check()
        print("generated sources current")
    elif args.command == "cubemx-ingest":
        artifact = ingest(args.cubemx_root, args.cubemx_identity, args.output)
        print(json.dumps({"identity": artifact["identity"], "pins": len(artifact["pins"]), "files": len(artifact["source_manifest"]["files"])}, indent=2))
    elif args.command == "cubemx-reconcile":
        artifact = ingest(args.cubemx_root, args.cubemx_identity, args.output)
        report = reconcile(artifact, Path("data/bundles/stm32g0b1"), Path("data/evidence.jsonl"), args.pin or ["PA0", "PA1", "PC0", "PC1"])
        print(json.dumps(report, indent=2))
        if report["errors"]:
            raise SystemExit(1)
    elif args.command == "cubemx-packet":
        artifact = ingest(args.cubemx_root, args.cubemx_identity)
        print(json.dumps(packet(artifact, args.pin), indent=2, sort_keys=True))
    elif args.command == "compatibility":
        report = write_reports()
        print(json.dumps({"cases": len(report["cases"]), "json": "reports/compatibility.json", "markdown": "reports/compatibility.md"}, indent=2))
    else:
        print(json.dumps(coverage(), indent=2))
