"""Deterministic KiCad 8 schematic backend.

This first backend revision emits a portable, flat, single-sheet schematic.
Symbols are generated and embedded from CopperScript part definitions, while
all coordinates and UUIDs remain backend-owned presentation details.
"""

from __future__ import annotations

from dataclasses import dataclass
from hashlib import sha256
import json
import re
from typing import Mapping
import uuid

from ..elaborate import elaborate
from ..model import (
    Board,
    ComponentInstance,
    DeviceDefinition,
    Direction,
    DriveMode,
    Endpoint,
    FlatElectricalView,
    PartDefinition,
    PackagePinDefinition,
    SignalDomain,
)
from ..quantities import Quantity
from .base import Artifact, ArtifactManifest


KICAD_SCHEMATIC_FORMAT = "20231120"
KICAD_TARGET_VERSION = "8.0"
_UUID_SEED = b"CopperScript KiCad schematic backend v0.1\0"


@dataclass(frozen=True, slots=True)
class KiCadSchematicOptions:
    page: str = "A4"
    columns: int = 3

    def __post_init__(self) -> None:
        if self.columns < 1:
            raise ValueError("KiCad schematic columns must be at least one")


@dataclass(frozen=True, slots=True)
class _PinLayout:
    pin: PackagePinDefinition
    electrical_type: str
    x: float
    y: float
    angle: int
    outward: int


@dataclass(frozen=True, slots=True)
class _PartSymbol:
    part: PartDefinition
    library_id: str
    entry_name: str
    pins: tuple[_PinLayout, ...]
    half_width: float
    half_height: float


class KiCadSchematicBackend:
    """Generate a self-contained KiCad 8 ``.kicad_sch`` artifact."""

    name = "kicad-schematic"
    target_version = KICAD_TARGET_VERSION

    def __init__(self, options: KiCadSchematicOptions | None = None):
        self.options = options or KiCadSchematicOptions()

    def generate(self, board: Board) -> ArtifactManifest:
        flat = elaborate(board)
        content = _render(board, flat, self.options)
        filename = f"{_safe_name(board.name)}.kicad_sch"
        warnings = (
            (
                "Hierarchy was elaborated into a flat single-sheet schematic; "
                "the CopperScript IR remains hierarchical."
            ),
        ) if board.module_instances else ()
        return ArtifactManifest(
            backend=self.name,
            target_version="10.0" if any(flat.library[c.part].internal_pad_groups for c in flat.components) else self.target_version,
            artifacts=(Artifact(filename, "application/x-kicad-schematic", content),),
            warnings=warnings,
        )


def _render(
    board: Board, flat: FlatElectricalView, options: KiCadSchematicOptions
) -> str:
    # ``elaborate`` returns a FlatElectricalView. Avoid a second public backend
    # entry point accepting derived IR so hierarchy loss is always deliberate.
    library = flat.library
    components = tuple(sorted(flat.components, key=lambda item: item.ref))
    used_parts = {component.part for component in components}
    missing_parts = sorted(used_parts - set(library))
    if missing_parts:
        raise ValueError(f"cannot generate symbol for unknown part {missing_parts[0]!r}")
    symbols = {
        name: _part_symbol(library[name], flat.devices)
        for name in sorted(used_parts)
    }
    placements = _place_components(components, symbols, options.columns)
    root_uuid = _stable_uuid(board.name, "root")
    component_index = {component.ref: component for component in components}
    endpoint_nets: dict[Endpoint, str] = {}
    for net in flat.nets:
        for endpoint in net.endpoints:
            component = component_index.get(endpoint.component)
            part = library.get(component.part) if component else None
            physical_name = (
                _physical_pin_name(component, part, flat.devices, endpoint.pin)
                if component and part
                else None
            )
            endpoint_nets[
                Endpoint(endpoint.component, physical_name or endpoint.pin)
            ] = net.name

    lines = [
        "(kicad_sch",
        f"  (version {'20250610' if any(s.part.internal_pad_groups for s in symbols.values()) else KICAD_SCHEMATIC_FORMAT})",
        '  (generator "copperscript")',
        '  (generator_version "0.1.0")',
        f'  (uuid "{root_uuid}")',
        f"  (paper {_quote(options.page)})",
        "  (title_block",
        f"    (title {_quote(board.name)})",
        '    (comment 1 "Generated by CopperScript; edit the .copper source")',
        "  )",
        "  (lib_symbols",
    ]
    for symbol in symbols.values():
        lines.extend(_library_symbol_lines(symbol))
    lines.append("  )")

    for component in components:
        symbol = symbols.get(component.part)
        if symbol is None:
            continue
        x, y = placements[component.ref]
        for pin_layout in symbol.pins:
            endpoint = Endpoint(component.ref, pin_layout.pin.name)
            pin_x = x + pin_layout.x
            pin_y = y + pin_layout.y
            net_name = endpoint_nets.get(endpoint)
            if net_name is None:
                lines.extend(_no_connect_lines(board.name, endpoint, pin_x, pin_y))
                continue
            label_x = pin_x + pin_layout.outward * 2.54
            lines.extend(
                _wire_lines(board.name, endpoint, pin_x, pin_y, label_x, pin_y)
            )
            lines.extend(
                _label_lines(
                    board.name,
                    endpoint,
                    net_name,
                    label_x,
                    pin_y,
                    pin_layout.outward,
                )
            )

    for component in components:
        symbol = symbols.get(component.part)
        if symbol is not None:
            lines.extend(
                _component_symbol_lines(
                    board.name,
                    root_uuid,
                    component,
                    symbol,
                    placements[component.ref],
                )
            )

    lines.extend(
        [
            "  (sheet_instances",
            '    (path "/"',
            '      (page "1")',
            "    )",
            "  )",
            ")",
        ]
    )
    return "\n".join(lines) + "\n"


def _physical_pin_name(
    component: ComponentInstance,
    part: PartDefinition,
    devices: Mapping[str, DeviceDefinition],
    endpoint_name: str,
) -> str | None:
    if endpoint_name in part.pins:
        return endpoint_name
    unit_name, separator, terminal_name = endpoint_name.partition(".")
    device = devices.get(part.device or "")
    unit = device.units.get(unit_name) if device is not None and separator else None
    terminal = unit.terminals.get(terminal_name) if unit is not None else None
    if terminal is None:
        return None
    matches = [
        pin.name
        for pin in part.pins.values()
        if any(
            bond.pad == terminal.pad
            and (bond.when is None or bond.when.matches(component.modes))
            for bond in pin.bonds
        )
    ]
    return matches[0] if len(matches) == 1 else None


def _part_symbol(
    part: PartDefinition, devices: Mapping[str, DeviceDefinition]
) -> _PartSymbol:
    digest = sha256(part.name.encode("utf-8")).hexdigest()[:8]
    entry_name = f"{_safe_name(part.name)}_{digest}"
    ordered = tuple(sorted(part.pins.values(), key=_pin_sort_key))
    left_count = (len(ordered) + 1) // 2
    left = ordered[:left_count]
    right = ordered[left_count:]
    pitch = 2.54
    half_width = 7.62
    half_height = max(5.08, (max(len(left), len(right), 1) + 1) * pitch / 2)
    pins: list[_PinLayout] = []
    for index, pin in enumerate(left):
        pins.append(
            _PinLayout(
                pin,
                _pin_electrical_type(part, pin, devices),
                -(half_width + 2.54),
                _pin_y(index, len(left), pitch),
                0,
                -1,
            )
        )
    for index, pin in enumerate(right):
        pins.append(
            _PinLayout(
                pin,
                _pin_electrical_type(part, pin, devices),
                half_width + 2.54,
                _pin_y(index, len(right), pitch),
                180,
                1,
            )
        )
    return _PartSymbol(
        part=part,
        library_id=f"CopperScript:{entry_name}",
        entry_name=entry_name,
        pins=tuple(pins),
        half_width=half_width,
        half_height=half_height,
    )


def _library_symbol_lines(symbol: _PartSymbol) -> list[str]:
    part = symbol.part
    reference = _reference_prefix(part)
    footprint = part.footprints[0] if part.footprints else ""
    datasheet = part.source.url if part.source and part.source.url else ""
    description = part.manufacturer or f"CopperScript part {part.name}"
    lines = [
        f"    (symbol {_quote(symbol.library_id)}",
        "      (pin_names (offset 1.016))",
        "      (exclude_from_sim no)",
        f"      (in_bom {'yes' if part.assembled else 'no'})",
        "      (on_board yes)",
    ]
    if part.internal_pad_groups and part.assembled:
        groups = " ".join("(" + " ".join(_quote(n) for n in g.numbers) + ")"
                          for g in part.internal_pad_groups)
        lines.extend(["      (duplicate_pin_numbers_are_jumpers no)",
                      f"      (jumper_pin_groups {groups})"])
    lines.extend(
        _property_lines(
            6,
            "Reference",
            reference,
            -symbol.half_width,
            -(symbol.half_height + 2.54),
        )
    )
    lines.extend(
        _property_lines(
            6,
            "Value",
            part.name,
            -symbol.half_width,
            symbol.half_height + 2.54,
        )
    )
    lines.extend(_property_lines(6, "Footprint", footprint, 0, 0, hidden=True))
    lines.extend(_property_lines(6, "Datasheet", datasheet, 0, 0, hidden=True))
    lines.extend(_property_lines(6, "Description", description, 0, 0, hidden=True))
    lines.extend(
        [
            f"      (symbol {_quote(symbol.entry_name + '_0_1')}",
            "        (rectangle",
            f"          (start {_number(-symbol.half_width)} {_number(-symbol.half_height)})",
            f"          (end {_number(symbol.half_width)} {_number(symbol.half_height)})",
            "          (stroke (width 0.254) (type default))",
            "          (fill (type background))",
            "        )",
            "      )",
            f"      (symbol {_quote(symbol.entry_name + '_1_1')}",
        ]
    )
    for layout in symbol.pins:
        pin = layout.pin
        lines.extend(
            [
                f"        (pin {layout.electrical_type} line",
                f"          (at {_number(layout.x)} {_number(layout.y)} {layout.angle})",
                "          (length 2.54)",
                f"          (name {_quote(pin.name)} (effects (font (size 1.27 1.27))))",
                f"          (number {_quote(pin.number)} (effects (font (size 1.27 1.27))))",
                "        )",
            ]
        )
    lines.extend(["      )", "    )"])
    return lines


def _component_symbol_lines(
    board_name: str,
    root_uuid: str,
    component: ComponentInstance,
    symbol: _PartSymbol,
    position: tuple[float, float],
) -> list[str]:
    x, y = position
    symbol_uuid = _stable_uuid(board_name, "symbol", component.ref)
    value = _component_value(component, symbol.part)
    footprint = component.footprint or (
        symbol.part.footprints[0] if symbol.part.footprints else ""
    )
    datasheet = symbol.part.source.url if symbol.part.source and symbol.part.source.url else ""
    kicad_ref = _kicad_reference(component.ref)
    lines = [
        "  (symbol",
        f"    (lib_id {_quote(symbol.library_id)})",
        f"    (at {_number(x)} {_number(y)} 0)",
        "    (unit 1)",
        "    (exclude_from_sim no)",
        f"    (in_bom {'yes' if symbol.part.assembled else 'no'})",
        "    (on_board yes)",
        "    (dnp no)",
        f'    (uuid "{symbol_uuid}")',
    ]
    lines.extend(
        _property_lines(
            4,
            "Reference",
            kicad_ref,
            x - symbol.half_width,
            y - symbol.half_height - 2.54,
        )
    )
    lines.extend(
        _property_lines(
            4,
            "Value",
            value,
            x - symbol.half_width,
            y + symbol.half_height + 2.54,
        )
    )
    lines.extend(_property_lines(4, "Footprint", footprint, x, y, hidden=True))
    lines.extend(_property_lines(4, "Datasheet", datasheet, x, y, hidden=True))
    lines.extend(_property_lines(4, "Description", "", x, y, hidden=True))
    if kicad_ref != component.ref:
        lines.extend(
            _property_lines(4, "CopperScriptPath", component.ref, x, y, hidden=True)
        )
    for layout in symbol.pins:
        pin_uuid = _stable_uuid(board_name, "pin", component.ref, layout.pin.number)
        lines.extend(
            [
                f"    (pin {_quote(layout.pin.number)}",
                f'      (uuid "{pin_uuid}")',
                "    )",
            ]
        )
    lines.extend(
        [
            "    (instances",
            f"      (project {_quote(_safe_name(board_name))}",
            f'        (path "/{root_uuid}"',
            f"          (reference {_quote(kicad_ref)})",
            "          (unit 1)",
            "        )",
            "      )",
            "    )",
            "  )",
        ]
    )
    return lines


def _property_lines(
    indent: int,
    name: str,
    value: str,
    x: float,
    y: float,
    *,
    hidden: bool = False,
) -> list[str]:
    prefix = " " * indent
    lines = [
        f"{prefix}(property {_quote(name)} {_quote(value)}",
        f"{prefix}  (at {_number(x)} {_number(y)} 0)",
        f"{prefix}  (effects",
        f"{prefix}    (font (size 1.27 1.27))",
    ]
    if hidden:
        lines.append(f"{prefix}    (hide yes)")
    lines.extend([f"{prefix}  )", f"{prefix})"])
    return lines


def _wire_lines(
    board_name: str,
    endpoint: Endpoint,
    x1: float,
    y1: float,
    x2: float,
    y2: float,
) -> list[str]:
    item_uuid = _stable_uuid(board_name, "wire", str(endpoint))
    return [
        "  (wire",
        f"    (pts (xy {_number(x1)} {_number(y1)}) (xy {_number(x2)} {_number(y2)}))",
        "    (stroke (width 0) (type default))",
        f'    (uuid "{item_uuid}")',
        "  )",
    ]


def _label_lines(
    board_name: str,
    endpoint: Endpoint,
    net_name: str,
    x: float,
    y: float,
    outward: int,
) -> list[str]:
    item_uuid = _stable_uuid(board_name, "label", str(endpoint), net_name)
    angle = 180 if outward < 0 else 0
    justify = "right bottom" if outward < 0 else "left bottom"
    return [
        f"  (label {_quote(net_name)}",
        f"    (at {_number(x)} {_number(y)} {angle})",
        "    (fields_autoplaced yes)",
        f"    (effects (font (size 1.27 1.27)) (justify {justify}))",
        f'    (uuid "{item_uuid}")',
        "  )",
    ]


def _no_connect_lines(
    board_name: str, endpoint: Endpoint, x: float, y: float
) -> list[str]:
    item_uuid = _stable_uuid(board_name, "no-connect", str(endpoint))
    return [
        "  (no_connect",
        f"    (at {_number(x)} {_number(y)})",
        f'    (uuid "{item_uuid}")',
        "  )",
    ]


def _place_components(
    components: tuple[ComponentInstance, ...],
    symbols: dict[str, _PartSymbol],
    columns: int,
) -> dict[str, tuple[float, float]]:
    placements: dict[str, tuple[float, float]] = {}
    x_positions = [
        50.8 + index * (190.5 / max(columns - 1, 1)) for index in range(columns)
    ]
    y_cursor = 25.4
    for start in range(0, len(components), columns):
        row = components[start : start + columns]
        row_height = max(
            (symbols[item.part].half_height * 2 + 20.32 for item in row if item.part in symbols),
            default=30.48,
        )
        y = y_cursor + row_height / 2
        for index, component in enumerate(row):
            placements[component.ref] = (x_positions[index], y)
        y_cursor += row_height
    return placements


def _pin_electrical_type(
    part: PartDefinition,
    pin: PackagePinDefinition,
    devices: Mapping[str, DeviceDefinition],
) -> str:
    profiles = [pin.profile] if pin.profile else []
    device = devices.get(part.device or "")
    if device is not None:
        for bond in pin.bonds:
            pad = device.pads.get(bond.pad)
            if pad is not None:
                profiles.append(pad.profile)
    domains = frozenset().union(*(profile.domains for profile in profiles))
    directions = frozenset().union(*(profile.directions for profile in profiles))
    drive_modes = frozenset().union(*(profile.drive_modes for profile in profiles))
    if SignalDomain.POWER in domains and Direction.OUTPUT in directions:
        return "power_out"
    if (SignalDomain.POWER in domains or SignalDomain.GROUND in domains) and Direction.INPUT in directions:
        return "power_in"
    if Direction.BIDIRECTIONAL in directions:
        return "bidirectional"
    if DriveMode.OPEN_DRAIN in drive_modes:
        return "open_collector"
    if Direction.OUTPUT in directions:
        return "output"
    if Direction.INPUT in directions:
        return "input"
    if SignalDomain.ANALOG in domains:
        return "bidirectional"
    if Direction.PASSIVE in directions:
        return "passive"
    return "unspecified"


def _component_value(component: ComponentInstance, part: PartDefinition) -> str:
    if component.value is None:
        return part.name.rsplit(".", 1)[-1]
    if isinstance(component.value, Quantity):
        return str(component.value)
    return component.value


def _reference_prefix(part: PartDefinition) -> str:
    return {
        "passive.resistor": "R",
        "passive.capacitor": "C",
        "power.source": "PS",
    }.get(part.category, "U")


def _kicad_reference(reference: str) -> str:
    safe = re.sub(r"[^A-Za-z0-9_]", "_", reference)
    if not safe or not safe[0].isalpha():
        safe = f"U_{safe}"
    return safe


def _safe_name(value: str) -> str:
    safe = re.sub(r"[^A-Za-z0-9_]", "_", value).strip("_")
    return safe or "CopperScript"


def _stable_uuid(*parts: str) -> str:
    digest = bytearray(sha256(_UUID_SEED + "\0".join(parts).encode("utf-8")).digest()[:16])
    digest[6] = (digest[6] & 0x0F) | 0x40
    digest[8] = (digest[8] & 0x3F) | 0x80
    return str(uuid.UUID(bytes=bytes(digest)))


def _pin_sort_key(pin: PackagePinDefinition) -> tuple[tuple[int, object], ...]:
    return tuple(
        (0, int(piece)) if piece.isdigit() else (1, piece.casefold())
        for piece in re.split(r"(\d+)", pin.number)
        if piece
    )


def _pin_y(index: int, count: int, pitch: float) -> float:
    return (index - (count - 1) / 2) * pitch


def _number(value: float) -> str:
    text = f"{value:.4f}".rstrip("0").rstrip(".")
    return "0" if text == "-0" else text


def _quote(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)
