"""Public API for the CopperScript v0.1 compiler and PCB IR."""

from .compiler import compile_file, compile_source
from .erc import Diagnostic, Severity, check, has_errors
from .elaborate import elaborate
from .model import (
    Board,
    ComponentInstance,
    Constraint,
    ConstraintKind,
    Dependency,
    DeviceDefinition,
    Endpoint,
    ElaboratedModuleInstance,
    FlatElectricalView,
    Interface,
    InterfaceKind,
    ModuleInstance,
    MuxOption,
    ModuleDefinition,
    Net,
    PartDefinition,
    PartKind,
    PeripheralDefinition,
    PeripheralSelection,
    PeripheralSignalDefinition,
    PeripheralSignalSelection,
    PinDefinition,
    PinType,
    Supply,
    ep,
)
from .quantities import (
    Capacitance,
    Inductance,
    Length,
    Quantity,
    Resistance,
    Voltage,
    kiloohms,
    microfarads,
    microhenries,
    millimeters,
    millivolts,
    nanofarads,
    ohms,
    volts,
)
from .syntax import CopperScriptError, SourceLocation

__all__ = [
    "Board",
    "Capacitance",
    "ComponentInstance",
    "Constraint",
    "ConstraintKind",
    "CopperScriptError",
    "Diagnostic",
    "Dependency",
    "DeviceDefinition",
    "Endpoint",
    "ElaboratedModuleInstance",
    "FlatElectricalView",
    "Interface",
    "InterfaceKind",
    "Inductance",
    "Length",
    "ModuleInstance",
    "MuxOption",
    "ModuleDefinition",
    "Net",
    "PartDefinition",
    "PartKind",
    "PeripheralDefinition",
    "PeripheralSelection",
    "PeripheralSignalDefinition",
    "PeripheralSignalSelection",
    "PinDefinition",
    "PinType",
    "Quantity",
    "Resistance",
    "Severity",
    "SourceLocation",
    "Supply",
    "Voltage",
    "check",
    "compile_file",
    "compile_source",
    "ep",
    "elaborate",
    "has_errors",
    "kiloohms",
    "microfarads",
    "microhenries",
    "millimeters",
    "millivolts",
    "nanofarads",
    "ohms",
    "volts",
]
